export type LocText = { en: string; sr: string };

export type LibraryTrack = {
  id: string;
  title: LocText;
  composer: LocText;
  detail: LocText;
  src: string;
  credit: string;
  duration: number;
  featured?: boolean;
};

const tr = (en: string, sr: string): LocText => ({ en, sr });

function ia(item: string, file: string): string {
  return `https://archive.org/download/${item}/${file.split("/").map(encodeURIComponent).join("/")}`;
}

const MUSOPEN = "MusopenCollectionAsFlac";
const CHOPIN = "musopen-chopin";
const SEASONS = "The_Four_Seasons_Vivaldi-10361";
const NAVY = "LightCavalryOvertureAndOtherWarhorses";
const WASPS = "OvertureToTheWasps";

const local = (file: string) => `/audio/${file}`;
const pack = (file: string) => `/audio/library/${file}`;

/**
 * Real performances, not MIDI. Compositions are public domain;
 * recordings are CC0, CC BY-SA, U.S. government, Musopen PD, or PD 78s.
 */
export const LIBRARY: LibraryTrack[] = [
  {
    id: "danube",
    title: tr("The Blue Danube", "Плави Дунав"),
    composer: tr("Johann Strauss II", "Јохан Штраус II"),
    detail: tr("Op. 314 · orchestra", "Op. 314 · оркестар"),
    src: local("strauss-blue-danube.mp3"),
    credit: "Musopen · CC0",
    duration: 178,
    featured: true,
  },
  {
    id: "nachtmusik",
    title: tr("Eine kleine Nachtmusik", "Мала ноћна музика"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("K. 525 · I. Allegro", "K. 525 · I. Allegro"),
    src: local("mozart-kleine-nachtmusik.mp3"),
    credit: "Advent Chamber Orchestra · CC BY-SA",
    duration: 355,
    featured: true,
  },
  {
    id: "air",
    title: tr("Air on the G String", "Арија на Г струни"),
    composer: tr("J. S. Bach", "Ј. С. Бах"),
    detail: tr("from Orchestral Suite No. 3", "из Оркестарске свите бр. 3"),
    src: local("bach-air-on-the-g-string.mp3"),
    credit: "U.S. Air Force Band · public domain",
    duration: 183,
    featured: true,
  },
  {
    id: "moonlight",
    title: tr("Moonlight Sonata", "Месечева соната"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Op. 27 No. 2 · I. Adagio", "Op. 27 бр. 2 · I. Adagio"),
    src: local("beethoven-moonlight.mp3"),
    credit: "Paul Pitman / Musopen · public domain",
    duration: 336,
    featured: true,
  },
  {
    id: "igor",
    title: tr("Polovtsian Dances", "Половачке игре"),
    composer: tr("Alexander Borodin", "Александар Бородин"),
    detail: tr("from Prince Igor · Dance No. 8", "из Кнеза Игора · игра бр. 8"),
    src: pack("igor.mp3"),
    credit: "Staatskapelle Berlin, Leo Blech · public domain",
    duration: 240,
    featured: true,
  },
  {
    id: "beethoven5-i",
    title: tr("Symphony No. 5", "Симфонија бр. 5"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Op. 67 · I. Allegro con brio", "Op. 67 · I. Allegro con brio"),
    src: pack("beethoven5-i.mp3"),
    credit: "Musopen · public domain",
    duration: 500,
    featured: true,
  },
  {
    id: "spring-i",
    title: tr("Spring", "Пролеће"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · I. Allegro", "Четири годишња доба · I. Allegro"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_01_-_Spring_Mvt_1_Allegro.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 215,
    featured: true,
  },
  {
    id: "mountain-king",
    title: tr("In the Hall of the Mountain King", "У дворани планинског краља"),
    composer: tr("Edvard Grieg", "Едвард Григ"),
    detail: tr("Peer Gynt Suite No. 1", "Пер Гинт, свита бр. 1"),
    src: ia(MUSOPEN, "Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-04-InTheHallOfTheMountainKing.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 154,
    featured: true,
  },
  {
    id: "newworld-ii",
    title: tr("From the New World", "Из Новог света"),
    composer: tr("Antonín Dvořák", "Антоњин Дворжак"),
    detail: tr("Symphony No. 9 · II. Largo", "Симфонија бр. 9 · II. Largo"),
    src: pack("newworld-ii.mp3"),
    credit: "Musopen · public domain",
    duration: 694,
    featured: true,
  },
  {
    id: "toreador",
    title: tr("Toreador Song", "Песма тореадора"),
    composer: tr("Georges Bizet", "Жорж Бизе"),
    detail: tr("Carmen · Act II", "Кармен · чин II"),
    src: pack("toreador.mp3"),
    credit: "Musopen · CC0",
    duration: 270,
    featured: true,
  },
  {
    id: "jesu",
    title: tr("Jesu, Joy of Man's Desiring", "Исусе, радости човечије"),
    composer: tr("J. S. Bach", "Ј. С. Бах"),
    detail: tr("from Cantata BWV 147", "из кантате BWV 147"),
    src: pack("jesu.mp3"),
    credit: "Musopen · public domain",
    duration: 202,
  },
  {
    id: "badinerie",
    title: tr("Badinerie", "Бадинерија"),
    composer: tr("J. S. Bach", "Ј. С. Бах"),
    detail: tr("Orchestral Suite No. 2 · X", "Оркестарска свита бр. 2 · X"),
    src: pack("badinerie.mp3"),
    credit: "Musopen · public domain",
    duration: 83,
  },
  {
    id: "goldberg-aria",
    title: tr("Goldberg Variations — Aria", "Голдберг варијације — Арија"),
    composer: tr("J. S. Bach", "Ј. С. Бах"),
    detail: tr("BWV 988 · piano", "BWV 988 · клавир"),
    src: ia(MUSOPEN, "Bach_GoldbergVariations/JohannSebastianBach-01-GoldbergVariationsBwv.988-Aria.mp3"),
    credit: "Musopen · public domain",
    duration: 292,
  },
  {
    id: "albinoni",
    title: tr("Oboe Concerto in D minor", "Концерт за обоу у д-молу"),
    composer: tr("Tomaso Albinoni", "Томазо Албинони"),
    detail: tr("Op. 9 No. 2 · II. Adagio", "Op. 9 бр. 2 · II. Adagio"),
    src: pack("albinoni.mp3"),
    credit: "Musopen · public domain",
    duration: 257,
  },
  {
    id: "beethoven5-iv",
    title: tr("Symphony No. 5", "Симфонија бр. 5"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Op. 67 · IV. Allegro", "Op. 67 · IV. Allegro"),
    src: pack("beethoven5-iv.mp3"),
    credit: "Musopen · public domain",
    duration: 706,
  },
  {
    id: "pathetique-ii",
    title: tr("Pathétique Sonata", "Патетична соната"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Op. 13 · II. Adagio cantabile", "Op. 13 · II. Adagio cantabile"),
    src: pack("pathetique-ii.mp3"),
    credit: "Musopen · public domain",
    duration: 298,
  },
  {
    id: "coriolan",
    title: tr("Coriolan Overture", "Увертира Кориолан"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Op. 62 · orchestra", "Op. 62 · оркестар"),
    src: ia(MUSOPEN, "Beethoven_CoriolanOverture/LudwigVanBeethoven-CoriolanOverture.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 498,
  },
  {
    id: "egmont",
    title: tr("Egmont Overture", "Увертира Егмонт"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Op. 84 · orchestra", "Op. 84 · оркестар"),
    src: ia(MUSOPEN, "Beethoven_EgmontOvertureOp.84/LudwigVanBeethoven-EgmontOvertureOp.84.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 540,
  },
  {
    id: "eroica-i",
    title: tr("Eroica Symphony", "Ероика"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Symphony No. 3 · I. Allegro con brio", "Симфонија бр. 3 · I. Allegro con brio"),
    src: ia(MUSOPEN, "Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-01-AllegroConBrio.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 911,
  },
  {
    id: "eroica-ii",
    title: tr("Eroica Symphony", "Ероика"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Symphony No. 3 · II. Marcia funebre", "Симфонија бр. 3 · II. Marcia funebre"),
    src: ia(MUSOPEN, "Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-02-MarciaFunebreAdagioAssai.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 928,
  },
  {
    id: "eroica-iii",
    title: tr("Eroica Symphony", "Ероика"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Symphony No. 3 · III. Scherzo", "Симфонија бр. 3 · III. Scherzo"),
    src: ia(MUSOPEN, "Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-03-ScherzoAllegroVivace.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 349,
  },
  {
    id: "eroica-iv",
    title: tr("Eroica Symphony", "Ероика"),
    composer: tr("Ludwig van Beethoven", "Лудвиг ван Бетовен"),
    detail: tr("Symphony No. 3 · IV. Finale", "Симфонија бр. 3 · IV. Finale"),
    src: ia(MUSOPEN, "Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-04-FinaleAllegroMolto.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 704,
  },
  {
    id: "carmen-prelude",
    title: tr("Carmen Prelude", "Прелудијум Кармен"),
    composer: tr("Georges Bizet", "Жорж Бизе"),
    detail: tr("Act I · orchestra", "чин I · оркестар"),
    src: pack("carmen-prelude.mp3"),
    credit: "Musopen · public domain",
    duration: 125,
  },
  {
    id: "steppes",
    title: tr("In the Steppes of Central Asia", "У степама Средње Азије"),
    composer: tr("Alexander Borodin", "Александар Бородин"),
    detail: tr("symphonic poem", "симфонијска поема"),
    src: ia(MUSOPEN, "Borodin_InTheSteppesOfCentralAsia/AlexanderBorodin-InTheSteppesOfCentralAsia.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 458,
  },
  {
    id: "borodin-nocturne",
    title: tr("Nocturne", "Ноктурно"),
    composer: tr("Alexander Borodin", "Александар Бородин"),
    detail: tr("String Quartet No. 2 · III", "Гудачки квартет бр. 2 · III"),
    src: ia(MUSOPEN, "Borodin_StringQuartetNo.2inDMajor/AlexanderBorodin-StringQuartetNo.2InDMajor-03-NocturneAndante.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 547,
  },
  {
    id: "borodin-q2-i",
    title: tr("String Quartet No. 2", "Гудачки квартет бр. 2"),
    composer: tr("Alexander Borodin", "Александар Бородин"),
    detail: tr("I. Allegro moderato", "I. Allegro moderato"),
    src: ia(MUSOPEN, "Borodin_StringQuartetNo.2inDMajor/AlexanderBorodin-StringQuartetNo.2InDMajor-01-AllegroModerato.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 541,
  },
  {
    id: "brahms1-i",
    title: tr("Symphony No. 1", "Симфонија бр. 1"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 68 · I. Un poco sostenuto", "Op. 68 · I. Un poco sostenuto"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.1inCMinor/JohannesBrahms-SymphonyNo.1InCMinorOp.68-01-UnPocoSostenuto-Allegro.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 909,
  },
  {
    id: "brahms1-iii",
    title: tr("Symphony No. 1", "Симфонија бр. 1"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 68 · III. Un poco allegretto", "Op. 68 · III. Un poco allegretto"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.1inCMinor/JohannesBrahms-SymphonyNo.1InCMinorOp.68-03-UnPocoAllegrettoEGrazioso.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 295,
  },
  {
    id: "brahms1-iv",
    title: tr("Symphony No. 1", "Симфонија бр. 1"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 68 · IV. Adagio — Allegro", "Op. 68 · IV. Adagio — Allegro"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.1inCMinor/JohannesBrahms-SymphonyNo.1InCMinorOp.68-04-Adagio-PiAndante-AllegroNonTroppoMaConBrio.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 1016,
  },
  {
    id: "brahms2-iii",
    title: tr("Symphony No. 2", "Симфонија бр. 2"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 73 · III. Allegretto grazioso", "Op. 73 · III. Allegretto grazioso"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.2inDMajor/JohannesBrahms-SymphonyNo.2InDMajorOp.73-03-AllegrettoGraziosotake1.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 302,
  },
  {
    id: "brahms3-i",
    title: tr("Symphony No. 3", "Симфонија бр. 3"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 90 · I. Allegro con brio", "Op. 90 · I. Allegro con brio"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.3inFMajor/JohannesBrahms-SymphonyNo.3InFMajorOp.90-01-AllegroConBrio.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 605,
  },
  {
    id: "brahms3-iii",
    title: tr("Symphony No. 3", "Симфонија бр. 3"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 90 · III. Poco allegretto", "Op. 90 · III. Poco allegretto"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.3inFMajor/JohannesBrahms-SymphonyNo.3InFMajorOp.90-03-PocoAllegretto.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 370,
  },
  {
    id: "brahms4-i",
    title: tr("Symphony No. 4", "Симфонија бр. 4"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 98 · I. Allegro non troppo", "Op. 98 · I. Allegro non troppo"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.4inEMinor/JohannesBrahms-SymphonyNo.4InEMinorOp.98-01-AllegroNonTroppo.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 760,
  },
  {
    id: "brahms4-iv",
    title: tr("Symphony No. 4", "Симфонија бр. 4"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 98 · IV. Allegro energico", "Op. 98 · IV. Allegro energico"),
    src: ia(MUSOPEN, "Brahms_SymphonyNo.4inEMinor/JohannesBrahms-SymphonyNo.4InEMinorOp.98-04-AllegroEnergicoEPassionato.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 667,
  },
  {
    id: "tragic",
    title: tr("Tragic Overture", "Трагична увертира"),
    composer: tr("Johannes Brahms", "Јоханес Брамс"),
    detail: tr("Op. 81 · orchestra", "Op. 81 · оркестар"),
    src: ia(MUSOPEN, "Brahms_TragicOverture/JohannesBrahms-TragicOverture.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 829,
  },
  {
    id: "nocturne-9-2",
    title: tr("Nocturne in E-flat", "Ноктурно у Ес-дуру"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 9 No. 2 · piano", "Op. 9 бр. 2 · клавир"),
    src: ia(CHOPIN, "Nocturne Op. 9 no. 2 in E flat major.mp3"),
    credit: "Musopen · CC0",
    duration: 276,
  },
  {
    id: "minute-waltz",
    title: tr("Minute Waltz", "Минут-валцер"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 64 No. 1 · piano", "Op. 64 бр. 1 · клавир"),
    src: ia(CHOPIN, "Waltz Op. 64 no. 1 in D flat major.mp3"),
    credit: "Musopen · CC0",
    duration: 107,
  },
  {
    id: "heroic",
    title: tr("Heroic Polonaise", "Херојска полонеза"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 53 · piano", "Op. 53 · клавир"),
    src: ia(CHOPIN, "PolonaiseOp.53InAFlatMajorheroic.mp3"),
    credit: "Musopen · CC0",
    duration: 438,
  },
  {
    id: "fantaisie",
    title: tr("Fantaisie-Impromptu", "Фантазија-импромпту"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 66 · piano", "Op. 66 · клавир"),
    src: ia(CHOPIN, "Fantasie Impromptu Op. 66.mp3"),
    credit: "Musopen · CC0",
    duration: 326,
  },
  {
    id: "raindrop",
    title: tr("Raindrop Prelude", "Прелудијум Кишна кап"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 28 No. 15 · piano", "Op. 28 бр. 15 · клавир"),
    src: ia(CHOPIN, "Prelude Op. 28 no. 15.mp3"),
    credit: "Musopen · CC0",
    duration: 295,
  },
  {
    id: "waltz-64-2",
    title: tr("Waltz in C-sharp minor", "Валцер у цис-молу"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 64 No. 2 · piano", "Op. 64 бр. 2 · клавир"),
    src: ia(CHOPIN, "Waltz Op. 64 no. 2 in C sharp minor.mp3"),
    credit: "Musopen · CC0",
    duration: 230,
  },
  {
    id: "ballade-1",
    title: tr("Ballade No. 1", "Балада бр. 1"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 23 · piano", "Op. 23 · клавир"),
    src: ia(CHOPIN, "Ballade no. 1 - Op. 23.mp3"),
    credit: "Musopen · CC0",
    duration: 613,
  },
  {
    id: "nocturne-27-2",
    title: tr("Nocturne in D-flat", "Ноктурно у Дес-дуру"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 27 No. 2 · piano", "Op. 27 бр. 2 · клавир"),
    src: ia(CHOPIN, "NocturneOp27No2.mp3"),
    credit: "Musopen · CC0",
    duration: 377,
  },
  {
    id: "grande-valse",
    title: tr("Grande valse brillante", "Велики сјајни валцер"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 18 · piano", "Op. 18 · клавир"),
    src: ia(CHOPIN, "Grande Valse Brilliante Op.18 In E flat major.mp3"),
    credit: "Musopen · CC0",
    duration: 319,
  },
  {
    id: "waltz-69-1",
    title: tr("Waltz in A-flat", "Валцер у Ас-дуру"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 69 No. 1 · L'Adieu", "Op. 69 бр. 1 · L'Adieu"),
    src: ia(CHOPIN, "Waltz Op. 69 no. 1 in A flat major.mp3"),
    credit: "Musopen · CC0",
    duration: 248,
  },
  {
    id: "nocturne-48-1",
    title: tr("Nocturne in C minor", "Ноктурно у ц-молу"),
    composer: tr("Frédéric Chopin", "Фредерик Шопен"),
    detail: tr("Op. 48 No. 1 · piano", "Op. 48 бр. 1 · клавир"),
    src: ia(CHOPIN, "Nocturne Op. 48 no. 1 in C minor.mp3"),
    credit: "Musopen · CC0",
    duration: 379,
  },
  {
    id: "newworld-i",
    title: tr("From the New World", "Из Новог света"),
    composer: tr("Antonín Dvořák", "Антоњин Дворжак"),
    detail: tr("Symphony No. 9 · I. Adagio — Allegro", "Симфонија бр. 9 · I. Adagio — Allegro"),
    src: pack("newworld-i.mp3"),
    credit: "Musopen · public domain",
    duration: 604,
  },
  {
    id: "american-i",
    title: tr("American Quartet", "Амерички квартет"),
    composer: tr("Antonín Dvořák", "Антоњин Дворжак"),
    detail: tr("Op. 96 · I. Allegro ma non troppo", "Op. 96 · I. Allegro ma non troppo"),
    src: ia(MUSOPEN, "Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-01-AllegroMaNonTroppo.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 475,
  },
  {
    id: "american-ii",
    title: tr("American Quartet", "Амерички квартет"),
    composer: tr("Antonín Dvořák", "Антоњин Дворжак"),
    detail: tr("Op. 96 · II. Lento", "Op. 96 · II. Lento"),
    src: ia(MUSOPEN, "Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-02-Lento.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 471,
  },
  {
    id: "american-iii",
    title: tr("American Quartet", "Амерички квартет"),
    composer: tr("Antonín Dvořák", "Антоњин Дворжак"),
    detail: tr("Op. 96 · III. Molto vivace", "Op. 96 · III. Molto vivace"),
    src: ia(MUSOPEN, "Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-03-MoltoVivace.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 250,
  },
  {
    id: "american-iv",
    title: tr("American Quartet", "Амерички квартет"),
    composer: tr("Antonín Dvořák", "Антоњин Дворжак"),
    detail: tr("Op. 96 · IV. Finale", "Op. 96 · IV. Finale"),
    src: ia(MUSOPEN, "Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-04-Finale-VivaceMaNonTroppo.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 351,
  },
  {
    id: "morning",
    title: tr("Morning Mood", "Јутарње расположење"),
    composer: tr("Edvard Grieg", "Едвард Григ"),
    detail: tr("Peer Gynt Suite No. 1", "Пер Гинт, свита бр. 1"),
    src: ia(MUSOPEN, "Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-01-Morning.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 229,
  },
  {
    id: "aase",
    title: tr("Åse's Death", "Смрт Осе"),
    composer: tr("Edvard Grieg", "Едвард Григ"),
    detail: tr("Peer Gynt Suite No. 1", "Пер Гинт, свита бр. 1"),
    src: ia(MUSOPEN, "Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-02-AasesDeath.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 273,
  },
  {
    id: "anitra",
    title: tr("Anitra's Dance", "Анитрин плес"),
    composer: tr("Edvard Grieg", "Едвард Григ"),
    detail: tr("Peer Gynt Suite No. 1", "Пер Гинт, свита бр. 1"),
    src: ia(MUSOPEN, "Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-03-AnitrasDream.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 239,
  },
  {
    id: "lark-i",
    title: tr("The Lark", "Шева"),
    composer: tr("Joseph Haydn", "Јозеф Хајдн"),
    detail: tr("Op. 64 No. 5 · I. Allegro moderato", "Op. 64 бр. 5 · I. Allegro moderato"),
    src: ia(MUSOPEN, "Haydn_StringQuartetInDMajorOp.64/JosephHaydn-StringQuartetInDOp.645H363Lark-01-AllegroModerato.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 371,
  },
  {
    id: "lark-iii",
    title: tr("The Lark", "Шева"),
    composer: tr("Joseph Haydn", "Јозеф Хајдн"),
    detail: tr("Op. 64 No. 5 · III. Menuetto", "Op. 64 бр. 5 · III. Menuetto"),
    src: ia(MUSOPEN, "Haydn_StringQuartetInDMajorOp.64/JosephHaydn-StringQuartetInDOp.645H363Lark-03-MenuettoAllegretto.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 226,
  },
  {
    id: "mars",
    title: tr("Mars, the Bringer of War", "Марс, доносилац рата"),
    composer: tr("Gustav Holst", "Густав Холст"),
    detail: tr("The Planets · I", "Планете · I"),
    src: pack("mars.mp3"),
    credit: "Musopen · public domain",
    duration: 498,
  },
  {
    id: "jupiter",
    title: tr("Jupiter, the Bringer of Jollity", "Јупитер, доносилац радости"),
    composer: tr("Gustav Holst", "Густав Холст"),
    detail: tr("The Planets · IV", "Планете · IV"),
    src: pack("jupiter.mp3"),
    credit: "Musopen · public domain",
    duration: 508,
  },
  {
    id: "hungarian-rhapsody-2",
    title: tr("Hungarian Rhapsody No. 2", "Мађарска рапсодија бр. 2"),
    composer: tr("Franz Liszt", "Франц Лист"),
    detail: tr("orchestra · U.S. Navy Band", "оркестар · У. С. Navy Band"),
    src: ia(NAVY, "HungarianRhapsodyNo2.mp3"),
    credit: "U.S. Navy Band · public domain",
    duration: 545,
  },
  {
    id: "hebrides",
    title: tr("The Hebrides", "Хебриди"),
    composer: tr("Felix Mendelssohn", "Феликс Менделсон"),
    detail: tr("Fingal's Cave · overture", "Фингалова пећина · увертира"),
    src: ia(MUSOPEN, "Mendelssohn_Hebrides/FelixMendelssohn-HebridesOvertureFingalsCave.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 682,
  },
  {
    id: "italian-i",
    title: tr("Italian Symphony", "Италијанска симфонија"),
    composer: tr("Felix Mendelssohn", "Феликс Менделсон"),
    detail: tr("Symphony No. 4 · I. Allegro vivace", "Симфонија бр. 4 · I. Allegro vivace"),
    src: ia(MUSOPEN, "Mendelssohn_ItalianSymphony/FelixMendelssohn-SymphonyNo.4InAMajorOp.90italian-01-AllegroVivace.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 463,
  },
  {
    id: "italian-ii",
    title: tr("Italian Symphony", "Италијанска симфонија"),
    composer: tr("Felix Mendelssohn", "Феликс Менделсон"),
    detail: tr("Symphony No. 4 · II. Andante con moto", "Симфонија бр. 4 · II. Andante con moto"),
    src: ia(MUSOPEN, "Mendelssohn_ItalianSymphony/FelixMendelssohn-SymphonyNo.4InAMajorOp.90italian-02-AndanteConMoto.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 347,
  },
  {
    id: "italian-iv",
    title: tr("Italian Symphony", "Италијанска симфонија"),
    composer: tr("Felix Mendelssohn", "Феликс Менделсон"),
    detail: tr("Symphony No. 4 · IV. Saltarello", "Симфонија бр. 4 · IV. Saltarello"),
    src: ia(MUSOPEN, "Mendelssohn_ItalianSymphony/FelixMendelssohn-SymphonyNo.4InAMajorOp.90italian-04-Saltarellopresto.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 367,
  },
  {
    id: "scottish-ii",
    title: tr("Scottish Symphony", "Шкотска симфонија"),
    composer: tr("Felix Mendelssohn", "Феликс Менделсон"),
    detail: tr("Symphony No. 3 · II. Vivace non troppo", "Симфонија бр. 3 · II. Vivace non troppo"),
    src: ia(MUSOPEN, "Mendelssohn_ScottishSymphony/FelixMendelssohn-SymphonyNo.3InAMinorscottishOp.56-02-VivaceNonTroppo.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 264,
  },
  {
    id: "scottish-iv",
    title: tr("Scottish Symphony", "Шкотска симфонија"),
    composer: tr("Felix Mendelssohn", "Феликс Менделсон"),
    detail: tr("Symphony No. 3 · IV. Allegro vivacissimo", "Симфонија бр. 3 · IV. Allegro vivacissimo"),
    src: ia(MUSOPEN, "Mendelssohn_ScottishSymphony/FelixMendelssohn-SymphonyNo.3InAMinorscottishOp.56-04-AllegroVivacissimo.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 682,
  },
  {
    id: "wedding-march",
    title: tr("Wedding March", "Свадбени марш"),
    composer: tr("Felix Mendelssohn", "Феликс Менделсон"),
    detail: tr("A Midsummer Night's Dream", "Сан летње ноћи"),
    src: pack("wedding-march.mp3"),
    credit: "European Archive / Musopen · public domain",
    duration: 293,
  },
  {
    id: "figaro",
    title: tr("The Marriage of Figaro", "Фигарова женидба"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("Overture · K. 492", "Увертира · K. 492"),
    src: ia(MUSOPEN, "Mozart_MarriageOfFigaro/WolfgangAmadeusMozart-MarriageOfFigaro.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 241,
  },
  {
    id: "magic-flute",
    title: tr("The Magic Flute", "Чаробна фрула"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("Overture · K. 620", "Увертира · K. 620"),
    src: ia(MUSOPEN, "Mozart_MagicFluteOverture/WolfgangAmadeusMozart-MagicFluteOverture.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 400,
  },
  {
    id: "mozart-40-i",
    title: tr("Symphony No. 40", "Симфонија бр. 40"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("K. 550 · I. Molto allegro", "K. 550 · I. Molto allegro"),
    src: ia(MUSOPEN, "Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-01-MoltoAllegro.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 358,
  },
  {
    id: "mozart-40-ii",
    title: tr("Symphony No. 40", "Симфонија бр. 40"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("K. 550 · II. Andante", "K. 550 · II. Andante"),
    src: ia(MUSOPEN, "Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-02-Andante.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 456,
  },
  {
    id: "mozart-40-iii",
    title: tr("Symphony No. 40", "Симфонија бр. 40"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("K. 550 · III. Menuetto", "K. 550 · III. Menuetto"),
    src: ia(MUSOPEN, "Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-03-MenuettoAllegretto.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 272,
  },
  {
    id: "mozart-40-iv",
    title: tr("Symphony No. 40", "Симфонија бр. 40"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("K. 550 · IV. Allegro assai", "K. 550 · IV. Allegro assai"),
    src: ia(MUSOPEN, "Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-04-AllegroAssai.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 284,
  },
  {
    id: "dissonance-i",
    title: tr("Dissonance Quartet", "Дисонантни квартет"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("K. 465 · I. Adagio — Allegro", "K. 465 · I. Adagio — Allegro"),
    src: ia(MUSOPEN, "Mozart_StringQuartetNo.19inCMajorK465/WolfgangAmadeusMozart-StringQuartetNo.19InCK465Dissonance-01-AdagioAllegro.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 513,
  },
  {
    id: "k421-i",
    title: tr("String Quartet No. 15", "Гудачки квартет бр. 15"),
    composer: tr("W. A. Mozart", "В. А. Моцарт"),
    detail: tr("K. 421 · I. Allegro moderato", "K. 421 · I. Allegro moderato"),
    src: ia(MUSOPEN, "Mozart_StringQuartetNo.15inDMinorK421/WolfgangAmadeusMozart-StringQuartetNo.15InDMinorK421-01-AllegroModerato.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 460,
  },
  {
    id: "bald-mountain",
    title: tr("Night on Bald Mountain", "Ноћ на голој гори"),
    composer: tr("Modest Mussorgsky", "Модест Мусоргски"),
    detail: tr("symphonic poem", "симфонијска поема"),
    src: pack("bald-mountain.mp3"),
    credit: "Musopen · public domain",
    duration: 733,
  },
  {
    id: "kiev",
    title: tr("The Great Gate of Kiev", "Велика кијевска капија"),
    composer: tr("Modest Mussorgsky", "Модест Мусоргски"),
    detail: tr("Pictures at an Exhibition", "Слике са изложбе"),
    src: pack("kiev.mp3"),
    credit: "Musopen · public domain",
    duration: 328,
  },
  {
    id: "rach-pc2-i",
    title: tr("Piano Concerto No. 2", "Клавирски концерт бр. 2"),
    composer: tr("Sergei Rachmaninoff", "Сергеј Рахмањинов"),
    detail: tr("Op. 18 · I. Moderato", "Op. 18 · I. Moderato"),
    src: pack("rach-pc2-i.mp3"),
    credit: "Musopen · public domain",
    duration: 654,
  },
  {
    id: "easter",
    title: tr("Russian Easter Festival", "Руска ускршња увертира"),
    composer: tr("Nikolai Rimsky-Korsakov", "Николај Римски-Корсаков"),
    detail: tr("Op. 36 · overture", "Op. 36 · увертира"),
    src: ia(MUSOPEN, "Rimsky-Korsakov_RussianOverture/NikolaiRimsky-korsakov-RussianEasterFestivalOvertureOp.36.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 936,
  },
  {
    id: "italian-girl",
    title: tr("The Italian Girl in Algiers", "Италијанка у Алжиру"),
    composer: tr("Gioachino Rossini", "Ђоакино Росини"),
    detail: tr("Overture · U.S. Navy Band", "Увертира · У. С. Navy Band"),
    src: ia(NAVY, "TheItalianGirlInAlgiersOverture.mp3"),
    credit: "U.S. Navy Band · public domain",
    duration: 501,
  },
  {
    id: "d664-i",
    title: tr("Piano Sonata in A major", "Клавирска соната у А-дуру"),
    composer: tr("Franz Schubert", "Франц Шуберт"),
    detail: tr("D. 664 · I. Allegro moderato", "D. 664 · I. Allegro moderato"),
    src: ia(MUSOPEN, "Schubert_SonataInAMajorD.664/FranzSchubert-SonataInAMajorD.664-01-AllegroModerato.mp3"),
    credit: "Paul Pitman / Musopen · public domain",
    duration: 466,
  },
  {
    id: "d664-ii",
    title: tr("Piano Sonata in A major", "Клавирска соната у А-дуру"),
    composer: tr("Franz Schubert", "Франц Шуберт"),
    detail: tr("D. 664 · II. Andante", "D. 664 · II. Andante"),
    src: ia(MUSOPEN, "Schubert_SonataInAMajorD.664/FranzSchubert-SonataInAMajorD.664-02-Andante.mp3"),
    credit: "Paul Pitman / Musopen · public domain",
    duration: 290,
  },
  {
    id: "moldau",
    title: tr("The Moldau", "Влтава"),
    composer: tr("Bedřich Smetana", "Беджих Сметана"),
    detail: tr("Má vlast · Vltava", "Моја домовина · Влтава"),
    src: ia(MUSOPEN, "Smetana_Vltava/BedichSmetana-MVlast-Vltava.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 770,
  },
  {
    id: "kaiserwalzer",
    title: tr("Emperor Waltz", "Царски валцер"),
    composer: tr("Johann Strauss II", "Јохан Штраус II"),
    detail: tr("Op. 437 · orchestra", "Op. 437 · оркестар"),
    src: pack("kaiserwalzer.mp3"),
    credit: "Musopen · public domain",
    duration: 180,
  },
  {
    id: "meditation",
    title: tr("Meditation on St. Wenceslas", "Медитација о св. Вацлаву"),
    composer: tr("Josef Suk", "Јозеф Сук"),
    detail: tr("Op. 35a · strings", "Op. 35a · гудачи"),
    src: ia(MUSOPEN, "Suk_Meditation/JosefSuk-Meditation.mp3"),
    credit: "Musopen String Quartet · public domain",
    duration: 405,
  },
  {
    id: "path-i",
    title: tr("Pathétique Symphony", "Патетична симфонија"),
    composer: tr("Pyotr Ilyich Tchaikovsky", "Петар Иљич Чајковски"),
    detail: tr("Symphony No. 6 · I. Adagio — Allegro", "Симфонија бр. 6 · I. Adagio — Allegro"),
    src: ia(MUSOPEN, "Tchaikovsky_SymphonyPathetique/PyotrIlyichTchaikovsky-SymphonyNo.6InBMinorOp.74pathtique-01-AdagioAllegroNonTroppo.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 1051,
  },
  {
    id: "path-ii",
    title: tr("Pathétique Symphony", "Патетична симфонија"),
    composer: tr("Pyotr Ilyich Tchaikovsky", "Петар Иљич Чајковски"),
    detail: tr("Symphony No. 6 · II. Allegro con grazia", "Симфонија бр. 6 · II. Allegro con grazia"),
    src: ia(MUSOPEN, "Tchaikovsky_SymphonyPathetique/PyotrIlyichTchaikovsky-SymphonyNo.6InBMinorOp.74pathtique-02-AllegroConGracia.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 496,
  },
  {
    id: "path-iii",
    title: tr("Pathétique Symphony", "Патетична симфонија"),
    composer: tr("Pyotr Ilyich Tchaikovsky", "Петар Иљич Чајковски"),
    detail: tr("Symphony No. 6 · III. Allegro molto vivace", "Симфонија бр. 6 · III. Allegro molto vivace"),
    src: ia(MUSOPEN, "Tchaikovsky_SymphonyPathetique/PyotrIlyichTchaikovsky-SymphonyNo.6InBMinorOp.74pathtique-03-AllegroMoltoVivace.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 593,
  },
  {
    id: "path-iv",
    title: tr("Pathétique Symphony", "Патетична симфонија"),
    composer: tr("Pyotr Ilyich Tchaikovsky", "Петар Иљич Чајковски"),
    detail: tr("Symphony No. 6 · IV. Finale", "Симфонија бр. 6 · IV. Finale"),
    src: ia(MUSOPEN, "Tchaikovsky_SymphonyPathetique/PyotrIlyichTchaikovsky-SymphonyNo.6InBMinorOp.74pathtique-04-FinaleAdagioLamentoso.mp3"),
    credit: "Musopen Symphony Orchestra · public domain",
    duration: 619,
  },
  {
    id: "swan-lake",
    title: tr("Swan Lake", "Лабудово језеро"),
    composer: tr("Pyotr Ilyich Tchaikovsky", "Петар Иљич Чајковски"),
    detail: tr("Act II · orchestra", "чин II · оркестар"),
    src: pack("swan-lake.mp3"),
    credit: "Musopen · public domain",
    duration: 250,
  },
  {
    id: "overture-1812",
    title: tr("1812 Overture", "Увертира 1812"),
    composer: tr("Pyotr Ilyich Tchaikovsky", "Петар Иљич Чајковски"),
    detail: tr("Op. 49 · orchestra", "Op. 49 · оркестар"),
    src: pack("overture-1812.mp3"),
    credit: "Musopen · public domain",
    duration: 999,
  },
  {
    id: "spring-ii",
    title: tr("Spring", "Пролеће"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · II. Largo", "Четири годишња доба · II. Largo"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_02_-_Spring_Mvt_2_Largo.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 172,
  },
  {
    id: "spring-iii",
    title: tr("Spring", "Пролеће"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · III. Allegro pastorale", "Четири годишња доба · III. Allegro pastorale"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_03_-_Spring_Mvt_3_Allegro_pastorale.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 254,
  },
  {
    id: "summer-i",
    title: tr("Summer", "Лето"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · I. Allegro non molto", "Четири годишња доба · I. Allegro non molto"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_04_-_Summer_Mvt_1_Allegro_non_molto.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 302,
  },
  {
    id: "summer-iii",
    title: tr("Summer", "Лето"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · III. Presto", "Четири годишња доба · III. Presto"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_06_-_Summer_Mvt_3_Presto.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 159,
  },
  {
    id: "autumn-i",
    title: tr("Autumn", "Јесен"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · I. Allegro", "Четири годишња доба · I. Allegro"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_07_-_Autumn_Mvt_1_Allegro.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 304,
  },
  {
    id: "winter-i",
    title: tr("Winter", "Зима"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · I. Allegro non molto", "Четири годишња доба · I. Allegro non molto"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_10_-_Winter_Mvt_1_Allegro_non_molto.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 209,
  },
  {
    id: "winter-ii",
    title: tr("Winter", "Зима"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · II. Largo", "Четири годишња доба · II. Largo"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_11_-_Winter_Mvt_2_Largo.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 132,
  },
  {
    id: "winter-iii",
    title: tr("Winter", "Зима"),
    composer: tr("Antonio Vivaldi", "Антонио Вивалди"),
    detail: tr("The Four Seasons · III. Allegro", "Четири годишња доба · III. Allegro"),
    src: ia(SEASONS, "John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_12_-_Winter_Mvt_3_Allegro.mp3"),
    credit: "John Harrison · Wichita State · CC BY-SA 3.0",
    duration: 208,
  },
  {
    id: "wasps",
    title: tr("The Wasps", "Осе"),
    composer: tr("Ralph Vaughan Williams", "Ралф Воан Вилијамс"),
    detail: tr("Overture · U.S. Navy Band", "Увертира · У. С. Navy Band"),
    src: ia(WASPS, "1-07VaughanWilliams_OvertureToTheWasps.mp3"),
    credit: "U.S. Navy Band · public domain",
    duration: 609,
  },
  {
    id: "oberon",
    title: tr("Oberon Overture", "Увертира Оберон"),
    composer: tr("Carl Maria von Weber", "Карл Марија фон Вебер"),
    detail: tr("orchestra · U.S. Navy Band", "оркестар · У. С. Navy Band"),
    src: ia(NAVY, "OberonOverture.mp3"),
    credit: "U.S. Navy Band · public domain",
    duration: 598,
  },
];

export function libraryTrack(id: string): LibraryTrack | undefined {
  return LIBRARY.find((track) => track.id === id);
}

export function trackText(
  track: LibraryTrack,
  locale: string,
  field: "title" | "composer" | "detail",
): string {
  const value = track[field];
  return locale === "sr" ? value.sr : value.en;
}

export function trackMatches(track: LibraryTrack, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  const hay = [
    track.title.en,
    track.title.sr,
    track.composer.en,
    track.composer.sr,
    track.detail.en,
    track.detail.sr,
    track.credit,
  ]
    .join(" ")
    .toLowerCase();
  return hay.includes(q);
}
