import { create } from "zustand";
import { EMPTY_NOTE, note } from "@/lib/celestial/loc-note";
import type { VizSnapshot } from "@/lib/celestial/types";

const quietBand = {
  enabled: true,
  sensitivity: 1.8,
  energy: 0,
  locked: false,
  playing: false,
  readiness: 0,
  weaveRate: 0,
};

export const initialSnapshot: VizSnapshot = {
  ready: false,
  fps: 60,
  paused: false,
  uiHidden: false,
  speed: 1,
  spinFactor: 0.01,
  linesPerSec: 6,
  maxWeave: 14,
  trailDuration: 40,
  orbitMode: "realistic",
  background: "milkyway",
  parallax: true,
  ambient: 1,
  bloom: 0.02,
  ringBrightness: 1.4,
  selectedCount: 0,
  canCreate: false,
  hiRes: true,
  hiResNote: note("maps.fetching"),
  autoOrbit: false,
  autoOrbitSpeed: 0.5,
  autoOrbitDir: "ccw",
  recording: false,
  recordElapsed: 0,
  recordNote: EMPTY_NOTE,
  recordFormat: "",
  videoAspect: "16:9",
  videoQuality: "1080",
  bodies: [],
  connections: [],
  audio: {
    trackName: "No track loaded",
    trackId: "",
    hasTrack: false,
    playing: false,
    muted: false,
    current: 0,
    duration: 0,
    volume: 0.8,
    rate: 1,
    rhythmEnabled: true,
    rhythmMode: "advanced",
    autoMix: true,
    mixStatus: "idle",
    mixNote: EMPTY_NOTE,
    mixVoice: "",
    bands: {
      bass: { ...quietBand, sensitivity: 1.8 },
      mid: { ...quietBand, sensitivity: 1.7 },
      high: { ...quietBand, sensitivity: 2.1 },
    },
  },
};

export const useVizStore = create<VizSnapshot>(() => initialSnapshot);
